### ISSUE TITLE
Any way to prevent outside styles from leaking in (i.e., shadow dom option?)

### ISSUE THREAD

**Issue by jasonhjohnson** [codewithkyle/notifyjs#7]
Hi,

Is it possible to encapsulate the styles so that outside styles don't leak into the snackbar-element?

Thanks,
Jason

**Comment by codewithkyle** [comment]
My knowledge of the Shadow DOM is limited but I do know that it doesn't prevent inheritable CSS properties from leaking in. Could you share an example of how outside styles are affecting the snackbar?

**Comment by jasonhjohnson** [comment]
@codewithkyle Hi Kyle, it looks like this onmouseover of the element when both a custom button and close button are present: https://www.dropbox.com/s/xme7uagb2cgblid/Screenshot%202020-02-11%2007.26.01.png?dl=0

With no custom and only the close button it's like this onmouseover: https://www.dropbox.com/s/npen3qoj7u15jdz/Screenshot%202020-02-11%2007.27.41.png?dl=0

I'm using Tailwind CSS without any customizations.

Thanks for caring!
-Jason

**Comment by codewithkyle** [comment]
I've seen this issue before. I believe the solution is to add a `position: relative;` property to the `<close-button>` and `<button>` elements.

The CSS from my components library uses a really aggressive CSS reset that forces everything to start as an inline blocks with a relative position. I really need to rethink that project...
